#!/usr/bin/env python3
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Steam Review Insights", layout="wide")

st.title("Steam Review Sentiment Dashboard")

uploaded = st.file_uploader("Upload sentiment_results.csv", type=["csv"])
if uploaded:
    df = pd.read_csv(uploaded)

    st.metric("Total Reviews", len(df))
    st.metric("Average Sentiment", f"{df['sentiment'].mean():.2f}")

    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.histogram(df, x="sentiment", nbins=40, title="Sentiment Distribution")
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        fig2 = px.box(df, y="sentiment", title="Sentiment Spread")
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("Examples")
    pos = df.sort_values("sentiment", ascending=False).head(5)
    neg = df.sort_values("sentiment", ascending=True).head(5)
    st.write("**Most Positive Reviews**")
    for _, r in pos.iterrows():
        st.markdown(f"✅ *{r['review'][:300]}* …")
    st.write("**Most Negative Reviews**")
    for _, r in neg.iterrows():
        st.markdown(f"❌ *{r['review'][:300]}* …")
else:
    st.info("Upload the CSV generated by analyze_sentiment.py")
